In [35]:
import numpy as np
import pandas as pd

In [36]:
df_awal = pd.read_csv('../data-collection-preprocessing/data-produk/product-goodgamingshop.csv')

In [37]:
df = df_awal.copy()

In [38]:
df.head()

Nama Produk  \
0  AKKO CS SWITCH MECHANICAL KEYBOARD - ROSE RED,...   
1  Zaku Switch Linear 63,5g PCB Mount - Keyboard ...   
2             GATERON SWITCH - PLATE MOUNT - Cokelat   
3  GATERON Optical MX Switch for Mechanical Gamin...   
4                       Ekstra Packaging Bubble Wrap   

                                            Kategori         Jumlah  \
0  Home|Komputer & Laptop|Aksesoris PC Gaming|Gam...  Terjual 7 rb+   
1  Home|Komputer & Laptop|Aksesoris PC Gaming|Gam...  Terjual 7 rb+   
2  Home|Komputer & Laptop|Aksesoris Komputer & La...  Terjual 4 rb+   
3  Home|Komputer & Laptop|Aksesoris Komputer & La...  Terjual 3 rb+   
4  Home|Perlengkapan Pesta|Bungkus Kemasan|Bubble...  Terjual 3 rb+   

  Harga Jual Harga Awal Diskon  \
0    Rp3.599    Rp4.600    22%   
1    Rp7.999   Rp10.499    24%   
2    Rp3.500    Rp3.500      0   
3    Rp3.500    Rp3.500      0   
4    Rp3.100    Rp3.100      0   

                                           Deskripsi Rating  Rating Counter  \
0  JAM OPERASIONAL\nSenin - Minggu : 10:00 - 19:0...      5    (166 rating)   
1  JAM OPERASIONAL\nSenin - Minggu : 10:00 - 19:0...    4.9     (92 rating)   
2  JAM OPERASIONAL\n✅ Senin - Minggu : 10:00 - 19...      5    (111 rating)   
3  JAM OPERASIONAL\n✅ Senin - Minggu : 10:00 - 19...      5     (89 rating)   
4  Deskripsi Ekstra Packaging Bubble Wrap\nHai ga...    4.9  (1.800 rating)   

                                                Link  
0  https://www.tokopedia.com/goodgamingshop/akko-...  
1  https://www.tokopedia.com/goodgamingshop/zaku-...  
2  https://www.tokopedia.com/goodgamingshop/gater...  
3  https://www.tokopedia.com/goodgamingshop/gater...  
4  https://www.tokopedia.com/goodgamingshop/ekstr...

In [39]:
df.shape

(2831, 10)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2831 entries, 0 to 2830
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Nama Produk     2831 non-null   object
 1   Kategori        2831 non-null   object
 2   Jumlah          2831 non-null   object
 3   Harga Jual      2831 non-null   object
 4   Harga Awal      2831 non-null   object
 5   Diskon          2831 non-null   object
 6   Deskripsi       2831 non-null   object
 7   Rating          2831 non-null   object
 8   Rating Counter  2831 non-null   object
 9   Link            2831 non-null   object
dtypes: object(10)
memory usage: 221.3+ KB


## Data Cleaning & Pre Processing:

In [41]:
df = df.rename(columns={
    'Nama Produk': 'nama_produk',
    'Kategori': 'kategori_produk',
    'Jumlah': 'jumlah_terjual',
    'Harga Jual': 'harga_jual',
    'Harga Awal': 'harga_awal',
    'Diskon': 'diskon',
    'Deskripsi': 'deskripsi',
    'Rating': 'rating',
    'Rating Counter': 'rating_counter',
    'Link': 'link'
})


In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2831 entries, 0 to 2830
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   nama_produk      2831 non-null   object
 1   kategori_produk  2831 non-null   object
 2   jumlah_terjual   2831 non-null   object
 3   harga_jual       2831 non-null   object
 4   harga_awal       2831 non-null   object
 5   diskon           2831 non-null   object
 6   deskripsi        2831 non-null   object
 7   rating           2831 non-null   object
 8   rating_counter   2831 non-null   object
 9   link             2831 non-null   object
dtypes: object(10)
memory usage: 221.3+ KB


In [43]:
# Menghitung jumlah duplikat berdasarkan kolom "Nama Produk"
jumlah_duplikat_produk = df.duplicated(subset=['nama_produk']).sum()

print("Jumlah Duplikat pada Kolom 'Nama Produk':", jumlah_duplikat_produk)


Jumlah Duplikat pada Kolom 'Nama Produk': 218


In [44]:
# Memilih baris yang merupakan duplikat berdasarkan kolom "Nama Produk"
duplikat_produk = df[df.duplicated(subset=['nama_produk'], keep=False)]

if not duplikat_produk.empty:
    # Menampilkan nama produk yang merupakan duplikat
    nama_produk_duplikat = duplikat_produk['nama_produk'].unique()
    print("Nama Produk yang Duplikat:")
    print(nama_produk_duplikat)
else:
    print("Tidak ada nama produk yang duplikat.")

Nama Produk yang Duplikat:
['Digital Alliance Throne Classic - Gaming Chair - Cokelat'
 'ONEX EV12 EVOLUTION KURSI GAMING CHAIR - Merah'
 'ONEX EV10 EVOLUTION SERIES KURSI GAMING CHAIR - Merah'
 'FANTECH Smart Power Strip Stop Kontak WIFI - SPS0101'
 'FANTECH Adaptor Kabel untuk LED Light Strip - LA1A01'
 'DURGOD K330W MECHANICAL KEYBOARD - Gaming Keyboard - Hitam, Yellow Switch'
 'CORSAIR 275R AIRFLOW WHITE icue H150i RGB PRO XT + CX750F WHITE'
 'ASUS ProArt PA24AC HDR Professional Monitor - WUXGA, HDR-10'
 'ASUS ProArt Display PA27AC HDR Professional Monitor 100% of sRGB'
 'ASUS ProArt Display PA329C 4K HDR Professional Monitor 100% Adobe RGB,'
 'ASUS ProArt PA32UC 4K HDR Professional Monitor 4K, HDR'
 'ASUS ProArt Display PA34VC Curved Professional Monitor - 100% sRGB'
 'MSI CREATOR PS321QR MONITOR 32" WQHD 1440p, 165Hz, IPS'
 'DarkFlash RC800 / RC-800 Kursi Gaming - Gaming Chair'
 'MSI OPTIX G273QF Monitor IPS 165Hz WQHD G-Sync Compatible'
 'Thrustmaster HOTAS Warthog™ Dual Throttl

In [45]:
# Menghapus data yang merupakan duplikat berdasarkan kolom "Nama Produk"
df_clean = df.copy()
df = df.drop_duplicates(subset=['nama_produk'])

# Mencetak informasi mengenai data yang telah dibersihkan
print("Jumlah baris sebelum penghapusan duplikat:", len(df_clean))
print("Jumlah baris setelah penghapusan duplikat:", len(df))

Jumlah baris sebelum penghapusan duplikat: 2831
Jumlah baris setelah penghapusan duplikat: 2613


In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2613 entries, 0 to 2822
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   nama_produk      2613 non-null   object
 1   kategori_produk  2613 non-null   object
 2   jumlah_terjual   2613 non-null   object
 3   harga_jual       2613 non-null   object
 4   harga_awal       2613 non-null   object
 5   diskon           2613 non-null   object
 6   deskripsi        2613 non-null   object
 7   rating           2613 non-null   object
 8   rating_counter   2613 non-null   object
 9   link             2613 non-null   object
dtypes: object(10)
memory usage: 224.6+ KB


In [47]:
# Memilih baris yang memiliki nilai 0 di kolom "Jumlah"
jumlah_nol = df[df['jumlah_terjual'] == 0]

if not jumlah_nol.empty:
    print("Baris dengan Nilai 0 pada Kolom 'Jumlah':")
    print(jumlah_nol)
else:
    print("Tidak ada baris dengan nilai 0 pada kolom 'Jumlah'.")

Tidak ada baris dengan nilai 0 pada kolom 'Jumlah'.


In [48]:
df['id_produk'] = pd.factorize(df['nama_produk'])[0] + 1
id_produk_col = df.pop('id_produk')
df.insert(0, 'id_produk', id_produk_col)
df.head()

id_produk                                        nama_produk  \
0          1  AKKO CS SWITCH MECHANICAL KEYBOARD - ROSE RED,...   
1          2  Zaku Switch Linear 63,5g PCB Mount - Keyboard ...   
2          3             GATERON SWITCH - PLATE MOUNT - Cokelat   
3          4  GATERON Optical MX Switch for Mechanical Gamin...   
4          5                       Ekstra Packaging Bubble Wrap   

                                     kategori_produk jumlah_terjual  \
0  Home|Komputer & Laptop|Aksesoris PC Gaming|Gam...  Terjual 7 rb+   
1  Home|Komputer & Laptop|Aksesoris PC Gaming|Gam...  Terjual 7 rb+   
2  Home|Komputer & Laptop|Aksesoris Komputer & La...  Terjual 4 rb+   
3  Home|Komputer & Laptop|Aksesoris Komputer & La...  Terjual 3 rb+   
4  Home|Perlengkapan Pesta|Bungkus Kemasan|Bubble...  Terjual 3 rb+   

  harga_jual harga_awal diskon  \
0    Rp3.599    Rp4.600    22%   
1    Rp7.999   Rp10.499    24%   
2    Rp3.500    Rp3.500      0   
3    Rp3.500    Rp3.500      0   
4    Rp3.100    Rp3.100      0   

                                           deskripsi rating  rating_counter  \
0  JAM OPERASIONAL\nSenin - Minggu : 10:00 - 19:0...      5    (166 rating)   
1  JAM OPERASIONAL\nSenin - Minggu : 10:00 - 19:0...    4.9     (92 rating)   
2  JAM OPERASIONAL\n✅ Senin - Minggu : 10:00 - 19...      5    (111 rating)   
3  JAM OPERASIONAL\n✅ Senin - Minggu : 10:00 - 19...      5     (89 rating)   
4  Deskripsi Ekstra Packaging Bubble Wrap\nHai ga...    4.9  (1.800 rating)   

                                                link  
0  https://www.tokopedia.com/goodgamingshop/akko-...  
1  https://www.tokopedia.com/goodgamingshop/zaku-...  
2  https://www.tokopedia.com/goodgamingshop/gater...  
3  https://www.tokopedia.com/goodgamingshop/gater...  
4  https://www.tokopedia.com/goodgamingshop/ekstr...

In [49]:
def transform_id_produk(id):
    return f'PI{id:04d}'

df['id_produk'] = df['id_produk'].apply(transform_id_produk)

In [50]:
df.head()

id_produk                                        nama_produk  \
0    PI0001  AKKO CS SWITCH MECHANICAL KEYBOARD - ROSE RED,...   
1    PI0002  Zaku Switch Linear 63,5g PCB Mount - Keyboard ...   
2    PI0003             GATERON SWITCH - PLATE MOUNT - Cokelat   
3    PI0004  GATERON Optical MX Switch for Mechanical Gamin...   
4    PI0005                       Ekstra Packaging Bubble Wrap   

                                     kategori_produk jumlah_terjual  \
0  Home|Komputer & Laptop|Aksesoris PC Gaming|Gam...  Terjual 7 rb+   
1  Home|Komputer & Laptop|Aksesoris PC Gaming|Gam...  Terjual 7 rb+   
2  Home|Komputer & Laptop|Aksesoris Komputer & La...  Terjual 4 rb+   
3  Home|Komputer & Laptop|Aksesoris Komputer & La...  Terjual 3 rb+   
4  Home|Perlengkapan Pesta|Bungkus Kemasan|Bubble...  Terjual 3 rb+   

  harga_jual harga_awal diskon  \
0    Rp3.599    Rp4.600    22%   
1    Rp7.999   Rp10.499    24%   
2    Rp3.500    Rp3.500      0   
3    Rp3.500    Rp3.500      0   
4    Rp3.100    Rp3.100      0   

                                           deskripsi rating  rating_counter  \
0  JAM OPERASIONAL\nSenin - Minggu : 10:00 - 19:0...      5    (166 rating)   
1  JAM OPERASIONAL\nSenin - Minggu : 10:00 - 19:0...    4.9     (92 rating)   
2  JAM OPERASIONAL\n✅ Senin - Minggu : 10:00 - 19...      5    (111 rating)   
3  JAM OPERASIONAL\n✅ Senin - Minggu : 10:00 - 19...      5     (89 rating)   
4  Deskripsi Ekstra Packaging Bubble Wrap\nHai ga...    4.9  (1.800 rating)   

                                                link  
0  https://www.tokopedia.com/goodgamingshop/akko-...  
1  https://www.tokopedia.com/goodgamingshop/zaku-...  
2  https://www.tokopedia.com/goodgamingshop/gater...  
3  https://www.tokopedia.com/goodgamingshop/gater...  
4  https://www.tokopedia.com/goodgamingshop/ekstr...

In [51]:
df.jumlah_terjual.unique()

array(['Terjual 7 rb+', 'Terjual 4 rb+', 'Terjual 3 rb+', 'Terjual 2 rb+',
       'Terjual 1 rb+', 'Terjual 750+', 'Terjual 500+', 'Terjual 250+',
       'Terjual 100+', 'Terjual 90+', 'Terjual 80+',
       '80+ barang berhasil terjual', 'Terjual 70+', 'Terjual 60+',
       'Terjual 50+', 'Terjual 40+', 'Terjual 30+', 'Terjual 29',
       'Terjual 28', 'Terjual 27', 'Terjual 26', 'Terjual 25',
       'Terjual 24', 'Terjual 23', 'Terjual 22', 'Terjual 21',
       'Terjual 20', 'Terjual 19', 'Terjual 18', 'Terjual 17',
       'Terjual 16', 'Terjual 15', 'Terjual 13', 'Terjual 14',
       'Terjual 12', '12 barang berhasil terjual', 'Terjual 11',
       'Terjual 10', 'Terjual 9', 'Terjual 8', 'Terjual 7', 'Terjual 6',
       'Terjual 5', '6 barang berhasil terjual', '0',
       '5 barang berhasil terjual', '4 barang berhasil terjual',
       'Terjual 4', 'Terjual 3', '3 barang berhasil terjual', 'Terjual 2',
       '2 barang berhasil terjual', 'Terjual 1',
       '1 barang berhasil terjual

In [52]:
import re

def clean_jumlah_terjual(value):
    if 'rb' in value:
        match = re.search(r'(\d+)', value)
        if match:
            return int(match.group()) * 1000
        else:
            return 0
    elif 'Diskusi' in value:
        return 0
    elif 'barang berhasil terjual' in value:
        match = re.search(r'(\d+)', value)
        if match:
            return int(match.group())
        else:
            return 0
    else:
        match = re.search(r'(\d+)', value)
        if match:
            return int(match.group())
        else:
            return 0
        
df['jumlah_terjual'] = df['jumlah_terjual'].apply(clean_jumlah_terjual)

df.jumlah_terjual.unique()

array([ 7000,  4000,  3000,  2000,  1000,   750,   500,   250,   100,
          90,    80,    70,    60,    50,    40,    30,    29,    28,
          27,    26,    25,    24,    23,    22,    21,    20,    19,
          18,    17,    16,    15,    13,    14,    12,    11,    10,
           9,     8,     7,     6,     5,     0,     4,     3,     2,
           1, 10000,  9000], dtype=int64)

In [53]:
df.harga_jual.unique()

array(['Rp3.599', 'Rp7.999', 'Rp3.500', 'Rp3.100', 'Rp6.400', 'Rp19.000',
       'Rp2.900', 'Rp957.000', 'Rp5.200', 'Rp95.000', 'Rp8.900',
       'Rp7.500', 'Rp5.000', 'Rp10.500', 'Rp259.000', 'Rp2.999',
       'Rp4.400', 'Rp39.000', 'Rp3.750', 'Rp2.950', 'Rp499.000',
       'Rp1.959.000', 'Rp849.000', 'Rp135.000', 'Rp199.000', 'Rp6.199',
       'Rp11.200', 'Rp54.000', 'Rp28.000', 'Rp269.000', 'Rp5.600',
       'Rp139.000', 'Rp26.400', 'Rp225.000', 'Rp15.000', 'Rp4.490',
       'Rp245.000', 'Rp699.000', 'Rp5.400', 'Rp6.799', 'Rp6.200',
       'Rp22.500', 'Rp165.000', 'Rp2.599', 'Rp740.000', 'Rp242.000',
       'Rp490.000', 'Rp360.000', 'Rp1.780.000', 'Rp320.000', 'Rp89.000',
       'Rp1.435.000', 'Rp50.000', 'Rp2.199.000', 'Rp149.000', 'Rp215.000',
       'Rp665.000', 'Rp649.000', 'Rp628.000', 'Rp4.200', 'Rp229.000',
       'Rp335.000', 'Rp559.000', 'Rp8.500', 'Rp675.000', 'Rp455.000',
       'Rp230.000', 'Rp595.000', 'Rp84.000', 'Rp145.000', 'Rp385.000',
       'Rp239.000', 'Rp195.000

In [54]:
def clean_harga_jual(value):
    value = value.replace('Rp', '').replace('.', '')
    return int(value)

df['harga_jual'] = df['harga_jual'].apply(clean_harga_jual)

df.harga_jual.unique()

array([    3599,     7999,     3500,     3100,     6400,    19000,
           2900,   957000,     5200,    95000,     8900,     7500,
           5000,    10500,   259000,     2999,     4400,    39000,
           3750,     2950,   499000,  1959000,   849000,   135000,
         199000,     6199,    11200,    54000,    28000,   269000,
           5600,   139000,    26400,   225000,    15000,     4490,
         245000,   699000,     5400,     6799,     6200,    22500,
         165000,     2599,   740000,   242000,   490000,   360000,
        1780000,   320000,    89000,  1435000,    50000,  2199000,
         149000,   215000,   665000,   649000,   628000,     4200,
         229000,   335000,   559000,     8500,   675000,   455000,
         230000,   595000,    84000,   145000,   385000,   239000,
         195000,  1290000,     6900,    94000,   325000,     8000,
         125000,   240000,   109000,   779000,     4450,  1665000,
         379000,  1295000,   289000,     9999,   669000,   377

In [55]:
df.harga_awal.unique()

array(['Rp4.600', 'Rp10.499', 'Rp3.500', 'Rp3.100', 'Rp6.400', 'Rp19.000',
       'Rp5.000', 'Rp1.299.000', 'Rp5.200', 'Rp95.000', 'Rp9.900',
       'Rp9.999', 'Rp10.500', 'Rp309.000', 'Rp2.999', 'Rp4.400',
       'Rp55.000', 'Rp3.750', 'Rp519.000', 'Rp2.049.000', 'Rp8.900',
       'Rp899.000', 'Rp135.000', 'Rp199.000', 'Rp6.199', 'Rp11.200',
       'Rp54.000', 'Rp28.000', 'Rp299.000', 'Rp5.600', 'Rp139.000',
       'Rp26.400', 'Rp225.000', 'Rp15.000', 'Rp4.490', 'Rp260.000',
       'Rp1.499.000', 'Rp999.000', 'Rp5.400', 'Rp7.000', 'Rp6.200',
       'Rp22.500', 'Rp7.500', 'Rp259.000', 'Rp165.000', 'Rp3.000',
       'Rp790.000', 'Rp242.000', 'Rp360.000', 'Rp1.780.000', 'Rp320.000',
       'Rp1.435.000', 'Rp50.000', 'Rp2.399.000', 'Rp149.000', 'Rp240.000',
       'Rp799.000', 'Rp695.000', 'Rp4.999', 'Rp229.000', 'Rp635.000',
       'Rp789.000', 'Rp8.500', 'Rp675.000', 'Rp455.000', 'Rp249.000',
       'Rp595.000', 'Rp2.950', 'Rp145.000', 'Rp569.000', 'Rp239.000',
       'Rp375.000', 'Rp6.

In [56]:
def clean_harga_awal(value):
    value = value.replace('Rp', '').replace('.', '')
    return int(value)

df['harga_awal'] = df['harga_awal'].apply(clean_harga_awal)

df.harga_awal.unique()

array([    4600,    10499,     3500,     3100,     6400,    19000,
           5000,  1299000,     5200,    95000,     9900,     9999,
          10500,   309000,     2999,     4400,    55000,     3750,
         519000,  2049000,     8900,   899000,   135000,   199000,
           6199,    11200,    54000,    28000,   299000,     5600,
         139000,    26400,   225000,    15000,     4490,   260000,
        1499000,   999000,     5400,     7000,     6200,    22500,
           7500,   259000,   165000,     3000,   790000,   242000,
         360000,  1780000,   320000,  1435000,    50000,  2399000,
         149000,   240000,   799000,   695000,     4999,   229000,
         635000,   789000,     8500,   675000,   455000,   249000,
         595000,     2950,   145000,   569000,   239000,   375000,
           6900,    94000,   325000,     8000,   125000,   499000,
         109000,   779000,     4450,  1969000,   599000,  1509000,
         590000,   500000,  1099000,   285000,   159000,     6

In [57]:
df.diskon.unique()

array(['22%', '24%', '0', '42%', '26%', '10%', '25%', '16%', '29%', '41%',
       '4%', '6%', '53%', '30%', '3%', '7%', '13%', '51%', '70%', '8%',
       '17%', '37%', '47%', '12%', '40%', '32%', '48%', '14%', '15%',
       '39%', '19%', '75%', '65%', '2%', '28%', '58%', '23%', '21%',
       '52%', '5%', '35%', '46%', '59%', '18%', '64%', '33%', '45%',
       '11%', '44%', '57%', '54%', '34%', '72%', '56%', '9%', '38%',
       '63%', '49%', '67%', '80%', '20%', '27%', '43%', '50%', '36%',
       '60%', '31%', '71%', '68%', '1%', '77%', '62%', '61%', '55%',
       '82%', '66%'], dtype=object)

In [58]:
def clean_diskon(value):
    value = value.replace('%', '')
    return float(value) / 100

df['diskon'] = df['diskon'].apply(clean_diskon)

df.diskon.unique()

array([0.22, 0.24, 0.  , 0.42, 0.26, 0.1 , 0.25, 0.16, 0.29, 0.41, 0.04,
       0.06, 0.53, 0.3 , 0.03, 0.07, 0.13, 0.51, 0.7 , 0.08, 0.17, 0.37,
       0.47, 0.12, 0.4 , 0.32, 0.48, 0.14, 0.15, 0.39, 0.19, 0.75, 0.65,
       0.02, 0.28, 0.58, 0.23, 0.21, 0.52, 0.05, 0.35, 0.46, 0.59, 0.18,
       0.64, 0.33, 0.45, 0.11, 0.44, 0.57, 0.54, 0.34, 0.72, 0.56, 0.09,
       0.38, 0.63, 0.49, 0.67, 0.8 , 0.2 , 0.27, 0.43, 0.5 , 0.36, 0.6 ,
       0.31, 0.71, 0.68, 0.01, 0.77, 0.62, 0.61, 0.55, 0.82, 0.66])

In [59]:
df.rating.unique()

array(['5', '4.9', '4.8', '4.6', '4.7',
       'JAM OPERASIONAL\nSenin - Minggu : 10:00 - 19:00\nPickup Gojeck Max Jam 16:30 Untuk Instant\n\nKTT / Content Mango Pomelo Mechanical Switch - 3 Pin ( Linear )\n\nspring 22mm\n\n37g Linear\nPre Travel 1.9mm\nTotal Travel 4 mm\n\nStem : POM\nUpper : PC\nBottom : PA66\n\n⚠️ Wajib Video Unboxing Uncut untuk menghindari Gagalnya claim garansi barang Jikalau barang terdapat Cacat fisik dari Pabrik / Pengiriman. ⚠️',
       '0', '4.5', '4.1',
       'JAM OPERASIONAL\nSenin - Minggu : 10:00 - 19:00\nPickup Gojeck Max Jam 16:30 Untuk Instant\n\nDTS Headphone:X 2.0 Surround Sound Speakers\nDengar lawanmu sebelum mereka menemukanmu dengan surround sound yang akurat dan soundscape yang sangat memukau(1).\n\nBahan yang Tahan Lama\nPRO Gaming Headset didesain dengan rangka aluminium dan baja untuk keseimbangan kenyamanan dan kekuatan yang sempurna.\n\n(1) Memerlukan PC Windows dan software Logitech G HUB.\n(2) Mungkin bervariasi berdasarkan kondisi peng

In [60]:
def clean_rating(rating, jumlah_terjual):
    if jumlah_terjual == 0:
        return 0.0
    try:
        cleaned_rating = float(rating)
        return cleaned_rating
    except ValueError:
        return 0.0

df['rating'] = df.apply(lambda row: clean_rating(row['rating'], row['jumlah_terjual']), axis=1)

df.rating.unique()

array([5. , 4.9, 4.8, 4.6, 4.7, 0. , 4.5, 4.1, 4. , 4.4, 4.3, 4.2, 3. ,
       3.3, 3.7, 1. , 2. ])

In [61]:
df.rating_counter.unique()

array(['(166 rating)', '(92 rating)', '(111 rating)', '(89 rating)',
       '(1.800 rating)', '(32 rating)', '(807 rating)', '(25 rating)',
       '(778 rating)', '(21 rating)', '(657 rating)', '(71 rating)',
       '(22 rating)', '(8 rating)', '(53 rating)', '(579 rating)',
       '(526 rating)', '(34 rating)', '(31 rating)', '(460 rating)',
       '(16 rating)', '(19 rating)', '(9 rating)', '(405 rating)',
       '(408 rating)', '(331 rating)', '(10 rating)', '(402 rating)',
       '(313 rating)', '(6 rating)', '(253 rating)', '(29 rating)',
       '(306 rating)', '(305 rating)', '(45 rating)', '(276 rating)',
       '(129 rating)', '(236 rating)', '(193 rating)', '(183 rating)',
       '(17 rating)', '(12 rating)', '(4 rating)', '(176 rating)',
       '(5 rating)', '(11 rating)', '(194 rating)', '(186 rating)',
       '(182 rating)', '(164 rating)', '(151 rating)', '(180 rating)',
       '(167 rating)', '(116 rating)', '(143 rating)', '(152 rating)',
       '(158 rating)', '(107 rat

In [62]:
def clean_rating_counter(counter, jumlah_terjual):
    if jumlah_terjual == 0:
        return 0
    try:
        if isinstance(counter, str):
            # Mencari nilai numerik dari string menggunakan regex
            matched = re.search(r'\((\d+) rating\)', counter)
            if matched:
                return int(matched.group(1))
            else:
                return 0
        else:
            return 0
    except ValueError:
        return 0

df['rating_counter'] = df.apply(lambda row: clean_rating_counter(row['rating_counter'], row['jumlah_terjual']), axis=1)

df.rating_counter.unique()

array([166,  92, 111,  89,   0,  32, 807,  25, 778,  21, 657,  71,  22,
         8,  53, 579, 526,  34,  31, 460,  16,  19,   9, 405, 408, 331,
        10, 402, 313,   6, 253,  29, 306, 305,  45, 276, 129, 236, 193,
       183,  17,  12,   4, 176,   5,  11, 194, 186, 182, 164, 151, 180,
       167, 116, 143, 152, 158, 107, 154, 184, 123, 121, 101, 146, 126,
       147, 119,  15,  87, 134, 104,   1, 122, 110, 117,  95,  84,  90,
       103,  88,  66, 106, 102,  76,  82,  72,  62,  79,  77,  14,  81,
        70,  61,   3,  35,  73,  58,  67,  44,  68,  54,  65,  59,  56,
        74,  37,  64,  50,  57,   2,  47,  63,  51,  42,  69,  40,  52,
        38,  30,  46,  55,  36,  49,  39,  43,  33,  27,  48,  41,  18,
        24,  28,  26,  23,  20,   7,  13, 138, 181, 234, 670, 310, 203,
       197, 191, 215, 179, 189, 127, 142, 114,  99,  98, 105,  83,  86,
        60], dtype=int64)

In [63]:
df[df['nama_produk'] == 'ASUS ROG STRIX XG49VQ Super Ultra-Wide HDR Gaming Monitor']

id_produk                                        nama_produk  \
2168    PI2169  ASUS ROG STRIX XG49VQ Super Ultra-Wide HDR Gam...   

                                 kategori_produk  jumlah_terjual  harga_jual  \
2168  Home|Komputer & Laptop|Monitor|Monitor LED               0    19304000   

      harga_awal  diskon                                          deskripsi  \
2168    19304000     0.0  Monitor LED ASUS Gaming ROG STRIX XG49VQ\nSpes...   

      rating  rating_counter  \
2168     0.0               0   

                                                   link  
2168  https://www.tokopedia.com/goodgamingshop/asus-...

In [64]:
df.head()

id_produk                                        nama_produk  \
0    PI0001  AKKO CS SWITCH MECHANICAL KEYBOARD - ROSE RED,...   
1    PI0002  Zaku Switch Linear 63,5g PCB Mount - Keyboard ...   
2    PI0003             GATERON SWITCH - PLATE MOUNT - Cokelat   
3    PI0004  GATERON Optical MX Switch for Mechanical Gamin...   
4    PI0005                       Ekstra Packaging Bubble Wrap   

                                     kategori_produk  jumlah_terjual  \
0  Home|Komputer & Laptop|Aksesoris PC Gaming|Gam...            7000   
1  Home|Komputer & Laptop|Aksesoris PC Gaming|Gam...            7000   
2  Home|Komputer & Laptop|Aksesoris Komputer & La...            4000   
3  Home|Komputer & Laptop|Aksesoris Komputer & La...            3000   
4  Home|Perlengkapan Pesta|Bungkus Kemasan|Bubble...            3000   

   harga_jual  harga_awal  diskon  \
0        3599        4600    0.22   
1        7999       10499    0.24   
2        3500        3500    0.00   
3        3500        3500    0.00   
4        3100        3100    0.00   

                                           deskripsi  rating  rating_counter  \
0  JAM OPERASIONAL\nSenin - Minggu : 10:00 - 19:0...     5.0             166   
1  JAM OPERASIONAL\nSenin - Minggu : 10:00 - 19:0...     4.9              92   
2  JAM OPERASIONAL\n✅ Senin - Minggu : 10:00 - 19...     5.0             111   
3  JAM OPERASIONAL\n✅ Senin - Minggu : 10:00 - 19...     5.0              89   
4  Deskripsi Ekstra Packaging Bubble Wrap\nHai ga...     4.9               0   

                                                link  
0  https://www.tokopedia.com/goodgamingshop/akko-...  
1  https://www.tokopedia.com/goodgamingshop/zaku-...  
2  https://www.tokopedia.com/goodgamingshop/gater...  
3  https://www.tokopedia.com/goodgamingshop/gater...  
4  https://www.tokopedia.com/goodgamingshop/ekstr...

In [66]:
df.to_csv('../data-collection-preprocessing/data-produk/clean_product-goodgamingshop.csv', index=False)